WITH T AS (
   SELECT
      REST_ID
    , ROUND(AVG(REVIEW_SCORE), 2) score
   FROM REST_REVIEW
   GROUP BY REST_ID
)


SELECT
   b.REST_ID
 , a.REST_NAME
 , a.FOOD_TYPE
 , a.FAVORITES
 , a.ADDRESS
 , b.score
FROM REST_INFO a , T b
WHERE 1=1
   AND a.REST_ID = b.REST_ID
   AND a.ADDRESS LIKE '서울%'
ORDER BY
   b.score DESC
 , a.FAVORITES DESC
