SELECT C.ID, D.FISH_NAME, C.LENGTH
FROM FISH_INFO AS C
INNER JOIN FISH_NAME_INFO AS D
    ON C.FISH_TYPE = D.FISH_TYPE
WHERE (C.FISH_TYPE, LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY C.ID